### ISSUE TITLE
Can you request resources for a specific task?

### ISSUE THREAD

**Issue by gcapes** [gcapes/matflow-learning#2]
@aplowman
Can resources be requested for specific tasks or part of tasks, or just for the whole workflow?

**Comment by aplowman** [comment]
Yes, you can add a `resources` block at the task-level as well. For example, this will use two cores for input file generators and output file parsers, and 16 cores for the "main" part of the task---the simulation in this case:

```yaml
- schema: simulate_VE_loading_damask
  resources:
    any:
      num_cores: 2
    main:
      num_cores: 16
  inputs:
    ...
```
